1. A small body of mass \(m\) was at rest on a horizontal surface. At time \(t=0\), a time varying force \(F(t)=bt\) is applied on the body, where \(b\) is a constant. The direction of the force forms a constant angle \(\alpha\) with the horizontal (see figure 1). The acceleration due to gravity is given by \(g\).

Figure 1: Figure for problem 1.

