

+++ ==ERROR: No output for this page==
4. (25 points.) Apply a "finite-volume" or the "control-volume" method to discretize the following model equation

\[\rho\!\left[\mathbf{u}\,\frac{\partial\mathbf{T}}{\partial\mathbf{x}}\right]= \mathbf{f}+\frac{\partial}{\partial\mathbf{x}}\!\left[\mathbf{K}\,\frac{ \partial\mathbf{T}}{\partial\mathbf{x}}\right]\]

Where \(\mathbf{f}\) and \(\mathbf{u}\) are known functions at all grid points; \(\rho\) is constant and \(\mathbf{K}\) is the thermal conductivity.
+++

