

**Problem 1:**

Using dimensional analysis; construct a constant, with units of length _only_, out of _all three_ of the following fundamental constants of Nature: \(\hbar\), \(G\), and \(c\). Here, \(\hbar\) is Planck's constant, which has dimensions of \([M][L]^{2}[T]^{-1}\), \(G\) is Newton's gravitational constant, which has dimensions of \([M]^{-1}[L]^{3}[T]^{-2}\), and \(c\) is the speed of light, with dimensions \([L][T]^{-1}\).

**Problem 2:**

How many hairs do you have on your head? _Do not Google the answer! Use knowledge you already have to make a good estimation of the answer. You must be within the right order of magnitude to receive full credit._

**Problem 3:**

Consider the vector \(\vec{A}\) shown in the figure, with magnitude given by \(A=\mathbf{10}\), that makes an angle of \(\theta=25^{\circ}\) with the \(x\)-axis.

* Find a vector, \(\vec{B}\), such that \(\vec{A}+\vec{B}=\mathbf{0}\). What is the magnitude of \(\vec{B}\)? Carefully sketch both \(\vec{A}\) and \(\vec{B}\), making sure they are proportional.
* Find a _unit_ vector, \(\widehat{u}\), such that \(\vec{A}+\widehat{u}=\mathbf{0}\).
* Let \(\vec{V}=5\,\,\hat{\mathbf{x}}-7\,\,\hat{\mathbf{y}}\). Compute \(\vec{A}\times\vec{V}\) and \(\vec{V}\times\vec{A}\). Compare your answers; does this make sense?

**Problem 4:**_Problem 1.62 in Young & Freedman_

A plane leaves the airport in Galisteo and flies \(\mathbf{170}\) km at \(68.0^{\circ}\) east of north; then it changes direction to fly \(230\) km at \(36.0^{\circ}\) south of east, after which it makes an immediate emergency landing in a pasture. When the airport sends out a rescue crew, in which direction and how far should this crew fly to go directly to this plane?

**Problem 5:**_Problem 1.76 in Young & Freedman_

Ricardo and Jane are standing under a tree in the middle of a pasture. An argument ensues, and they walk away in different directions. Ricardo walks \(26.0\) m in a direction \(60.0^{\circ}\) west of north. Jane walks \(16.0\) m in a direction \(30.0^{\circ}\) south of west. They then stop and turn to face each other.

* What is the distance between them?
* In what direction should Ricardo walk to go directly toward Jane?